config/routes.rb
Rails.application.routes.draw do

  
  resources :groups do 
    resources :group_expenses
  end
  resources :transactions
  resources :wallets
  resources :accounts
  resources :income, controller: "transactions", type: "income"
  resources :expense, controller: "transactions", type: "expense"
  resources :transfer, controller: "transactions", type: "transfer"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root to:"public#homepage"

  devise_for :users, controllers: {
    registrations: 'user/registrations',
    invitations: 'user/invitations',
  }  
          # get      '*path'       => redirect('/404') 
end

app/models/group.rb
class Group < ApplicationRecord
    has_many :group_members

    has_many :users, through: :group_members

    belongs_to :user

    has_many :group_expenses
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[ show edit update destroy ]
  before_action :set_user, only: %i[update edit]

  # GET /groups or /groups.json
  def index
    # byebug  
    @groups = current_user.groups
    @group_members=GroupMember.all
    # @group_members=@group.GroupMember.all
  end

  # GET /groups/1 or /groups/1.json
  def show
    # byebug  
    @group_members=@group.group_members
    # @group_members
  end

  # GET /groups/new
  def new
    @group = Group.new
    


  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups or /groups.json
  def create
    @group = Group.create(group_params)
    @group.user_id=current_user.id
    @group_expense.user_id=current_user.id
    
      if @group.save
        @group_member=GroupMember.new
        @group_member.user_id=current_user.id
        @group_member.group_id=@group.id
        @group_member.save
        # byebug
        redirect_to @group, notice: "Group was successfully created."
      else
        render :new, status: :unprocessable_entity 
      end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    if(group_params.has_key?(:email))
      # byebug
      if (User.find_by_email(group_params[:email]) != nil)
        @user=User.find_by_email(group_params[:email])
        @group_member=GroupMember.new
        @group_member.user_id=@user.id
        @group_member.group_id=@group.id
        @group_member.save
        redirect_to @group, notice: "User sucessfullly Added." 
      else
        # byebug
        @user = User.invite!(group_params, current_user)
        puts(@user.raw_invitation_token)
        @user=User.find_by_email(group_params[:email])
        @group_member=GroupMember.new
        @group_member.user_id=@user.id
        @group_member.group_id=@group.id
        @group_member.save
        redirect_to @group, notice: "Invitation has been sucesfully send" 
      end
    else
      if @group.update(group_params)
        redirect_to @group, notice: "Group was successfully updated." 
      else
        render :edit, status: :unprocessable_entity 
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy
      redirect_to groups_url, notice: "Group was successfully destroyed." 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      # byebug
      @group = Group.find(params[:id])
    end

    def set_user
      @group = Group.find(params[:id])
      @user = User.find_by_email(params[:email])
    end

    # Only allow a list of trusted parameters through.
    def group_params
      if(params[:group] != nil)
        params.require(:group).permit(:group_name)
      elsif params[:user] != nil
        params.require(:user).permit(:email)  
      end
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= simple_form_for(@group) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :group_name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Groups</h1>

<table>
  <thead>
    <tr>
      <th>Group name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.group_name %></td>
        <td><%= link_to 'Add User', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group)%></td> 
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<div data-controller="group">
<p>
  <strong>Group name:</strong>
  <%= @group.group_name %>
</p>
<h1>Groups Users</h1>

<table>
  <thead>
    <tr>
      <th>User Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @group_members.each do |group_member| %>
      <tr>
        <td><%= group_member.user_id=User.find(group_member.user_id).email %></td>
       
      </tr>
    <% end %>
  </tbody>
</table>

    <button class="btn btn-success btn-xs"  data-action="click->group#showFields">
      Add User
    </button>
  <div data-group-target="userField">
   <%=simple_form_for(:user, html: { method: :put }) do |f|%>
       <div class="form-inputs">
        <%= f.label :email %><br />
        <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
      </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
    <% end %>
  </div>
   <%# <button class="btn btn-success btn-xs"  data-action="click->group#showExpense">
      Create Expense
    </button> %>
  <%= link_to 'Create Expense',new_group_group_expense_path(@group) , class:"btn btn-success btn-xs"  %> |
</div>
<%# <%= link_to 'Edit', edit_group_path(@group) %> 
<%= link_to 'Back', groups_path %>