config/routes.rb
Rails.application.routes.draw do

  
  resources :groups do 
    resources :group_expenses
  end
  resources :transactions
  resources :wallets
  resources :accounts
  resources :income, controller: "transactions", type: "income"
  resources :expense, controller: "transactions", type: "expense"
  resources :transfer, controller: "transactions", type: "transfer"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root to:"public#homepage"

  devise_for :users, controllers: {
    registrations: 'user/registrations',
    invitations: 'user/invitations',
  }  
          # get      '*path'       => redirect('/404') 
end

app/models/wallet.rb
class Wallet < ApplicationRecord
    belongs_to :user
    has_many :transactions, as: :transaction_to
    has_many :transactions, as: :transaction_from

    validates :walletbalance,presence: true
end

app/controllers/wallets_controller.rb
class WalletsController < ApplicationController
  before_action :set_wallet, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /wallets or /wallets.json
  def index
    @wallet = current_user.wallet
  end

  # GET /wallets/1 or /wallets/1.json
  def show
    authorize @wallet
  end

  # GET /wallets/new
  def new
    @wallet =Wallet.new
    authorize @wallet
  end

  # GET /wallets/1/edit
  def edit
    authorize @wallet
  end


  # POST /wallets or /wallets.json
  def create 
    authorize @wallet
    @wallet = Wallet.new(wallet_params)
    @wallet.user_id=current_user.id

    if @wallet.save
      redirect_to @wallet, notice: "Wallet was successfully created." 
    else
      render :new, status: :unprocessable_entity 
    end
  end

  # PATCH/PUT /wallets/1 or /wallets/1.json
  def update

    if @wallet.update(wallet_params)
      redirect_to @wallet, notice: "Wallet was successfully updated." 
    else
      render :edit, status: :unprocessable_entity
    end
    
  end

  # DELETE /wallets/1 or /wallets/1.json
  def destroy
    authorize @wallet
    @wallet.destroy
  
   redirect_to wallets_url, notice: "Wallet was successfully destroyed." 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wallet
      @wallet = Wallet.find(params[:id])
    end
    # Only allow a list of trusted parameters through.
    def wallet_params
      params.require(:wallet).permit(:walletbalance)
    end
end

app/helpers/wallets_helper.rb
module WalletsHelper
end

app/views/wallets/_form.html.erb
<%= simple_form_for @wallet do |form| %>
  <% if @wallet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wallet.errors.count, "error") %> prohibited this wallet from being saved:</h2>

      <ul>
        <% @wallet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">

  <div class="col-4">
  </div>

  <div class="col-4">
    <div class="from-group">
      <%= form.label :walletbalance %>
      <%= form.number_field :walletbalance ,required: true, min: 1,class:"form-control"%>
    </div>

    <div class="actions">
       <%= form.button :submit, class: 'btn btn-success' %>
    </div>

    <% end %>
  </div>

  <div class="col-4">
  </div>
  
</div>
  

app/views/wallets/edit.html.erb
<h1>Editing Wallet</h1>

<%= render 'form', wallet: @wallet %>

<%= link_to 'Show', @wallet,class: 'btn btn-outline-info btn-xs'  %> |
<%= link_to 'Back', accounts_path ,class: 'btn btn-outline-success btn-xs'  %>

app/views/wallets/index.html.erb
<h1>Wallets</h1>

<table class="table table-bordered table-dark">
  <thead>
    <tr>
      <th scope="col">Walletbalance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= @wallet.walletbalance %></td>
      <td><%= link_to 'Show', @wallet %></td>
      <td><%= link_to 'Edit', edit_wallet_path(@wallet) , class: 'btn btn-outline-warning btn-xs'%></td>
      <%# <td><%= link_to 'Destroy', @wallet, method: :delete, data: { confirm: 'Are you sure?' } %>
    </tr>
  </tbody>
</table>

<br>

<%# <%= link_to 'New Wallet', new_wallet_path %> 

app/views/wallets/new.html.erb
<h1>New Wallet</h1>

<%= render 'form', wallet: @wallet %>

<%= link_to 'Back', wallets_path %>

app/views/wallets/show.html.erb
<div class="row">
  <div class="col-4">
  </div>
  <div class="col-4">
  <table class="table">
  <tbody>
    <tr>
      <th scope="row">Walletbalance:</th>
      <td><%= @wallet.walletbalance %></td>
    </tr>
  </tbody>
</table>
<%= link_to 'Edit', edit_wallet_path(@wallet) , class: 'btn btn-outline-warning btn-xs' %> | 
<%= link_to 'Back', accounts_path ,class: 'btn btn-outline-success btn-xs'  %>

  </div>

  <div class="col-4">
  </div>
  
</div>