config/routes.rb
Rails.application.routes.draw do

  
  resources :groups do 
    resources :group_expenses
  end
  resources :transactions
  resources :wallets
  resources :accounts
  resources :income, controller: "transactions", type: "income"
  resources :expense, controller: "transactions", type: "expense"
  resources :transfer, controller: "transactions", type: "transfer"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root to:"public#homepage"

  devise_for :users, controllers: {
    registrations: 'user/registrations',
    invitations: 'user/invitations',
  }  
          # get      '*path'       => redirect('/404') 
end

app/models/account.rb
class Account < ApplicationRecord
    belongs_to :user
    has_many :transactions, as: :transaction_to
    has_many :transactions, as: :transaction_from
    
    validates :accountnumber,:accountname, uniqueness: true

    validates :accountnumber, :accountname, :accountbalance, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/expense.rb
class Expense <  Transaction;
end

app/models/expense_member.rb
class ExpenseMember < ApplicationRecord
  belongs_to :group_expense 
  belongs_to :lenter,:class_name => 'User',:foreign_key => :lenter_id
  belongs_to :borror,:class_name => 'User',:foreign_key => :borror_id
end

app/models/group.rb
class Group < ApplicationRecord
    has_many :group_members

    has_many :users, through: :group_members

    belongs_to :user

    has_many :group_expenses
end

app/models/group_expense.rb
class GroupExpense < ApplicationRecord
    has_many :expense_members
    belongs_to :group
    belongs_to :user
end

app/models/group_member.rb
class GroupMember < ApplicationRecord
    belongs_to :user
    belongs_to :group
end

app/models/income.rb
class Income < Transaction
end

app/models/transaction.rb
class Transaction < ApplicationRecord
    
    self.inheritance_column = :type 
    
    enum category: [:Food,:Transportation,:Accommodation]
    belongs_to :user
    
    scope :expense, -> {where(type: 'Expense')}

    scope :income, -> {where(type: 'Income')}
    
    scope :transfer, -> {where(type: 'Transfer')}

    belongs_to :transaction_to, polymorphic: true,optional: true
    belongs_to :transaction_from, polymorphic: true,optional: true

    
     validates :transaction_amount,:transfer_from_id,:type,presence: true

 


    
    

end

app/models/transfer.rb
class Transfer < Transaction
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :accounts
         has_one :wallet
         has_many :transactions
         has_many :expenses ,class_name: 'Expense'
         has_many :incomes ,class_name: 'Income'
         has_many :transfers ,class_name: 'Transfer'
         delegate :expense,:income,:transfer,to: :transations
         
         has_many :group_members
         has_many :groups, through: :group_members  
         
         has_many :group_expenses
         has_many :expense_members
         
       


end

app/models/wallet.rb
class Wallet < ApplicationRecord
    belongs_to :user
    has_many :transactions, as: :transaction_to
    has_many :transactions, as: :transaction_from

    validates :walletbalance,presence: true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[ show edit update destroy ]
  before_action :set_user, only: %i[update edit]

  # GET /groups or /groups.json
  def index
    # byebug  
    @groups = current_user.groups
    @group_members=GroupMember.all
    # @group_members=@group.GroupMember.all
  end

  # GET /groups/1 or /groups/1.json
  def show
    # byebug  
    @group_members=@group.group_members
    # @group_members
  end

  # GET /groups/new
  def new
    @group = Group.new
    


  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups or /groups.json
  def create
    @group = Group.create(group_params)
    @group.user_id=current_user.id
    @group_expense.user_id=current_user.id
    
      if @group.save
        @group_member=GroupMember.new
        @group_member.user_id=current_user.id
        @group_member.group_id=@group.id
        @group_member.save
        # byebug
        redirect_to @group, notice: "Group was successfully created."
      else
        render :new, status: :unprocessable_entity 
      end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    if(group_params.has_key?(:email))
      # byebug
      if (User.find_by_email(group_params[:email]) != nil)
        @user=User.find_by_email(group_params[:email])
        @group_member=GroupMember.new
        @group_member.user_id=@user.id
        @group_member.group_id=@group.id
        @group_member.save
        redirect_to @group, notice: "User sucessfullly Added." 
      else
        # byebug
        @user = User.invite!(group_params, current_user)
        puts(@user.raw_invitation_token)
        @user=User.find_by_email(group_params[:email])
        @group_member=GroupMember.new
        @group_member.user_id=@user.id
        @group_member.group_id=@group.id
        @group_member.save
        redirect_to @group, notice: "Invitation has been sucesfully send" 
      end
    else
      if @group.update(group_params)
        redirect_to @group, notice: "Group was successfully updated." 
      else
        render :edit, status: :unprocessable_entity 
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy
      redirect_to groups_url, notice: "Group was successfully destroyed." 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      # byebug
      @group = Group.find(params[:id])
    end

    def set_user
      @group = Group.find(params[:id])
      @user = User.find_by_email(params[:email])
    end

    # Only allow a list of trusted parameters through.
    def group_params
      if(params[:group] != nil)
        params.require(:group).permit(:group_name)
      elsif params[:user] != nil
        params.require(:user).permit(:email)  
      end
    end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
    def index
        @sum = sumOpinion(@opinion)
        
    end
    def homepage
      if (user_signed_in?)
        @opinion =current_user.transactions.pluck(:type,:transaction_amount)
        @aggregate = aggregateOpinion(@opinion)
        @aggregate << ["Wallet",current_user.wallet.walletbalance]
        @aggregate<<["Current Balnce",current_user.accounts.sum(:accountbalance)-@aggregate[0][1].to_f]
      end
      @transaction=Transaction.new
      @accounts_name=current_user.accounts.pluck(:accountname,:id)
      @accounts_name.push([current_user.wallet.class.name,current_user.wallet.id])
    end
    def aggregateOpinion(array)
        result = [["Expense",0],["Income",0]]
        array.each do |i|
          if i[0] == "Expense"
            result[0][1] += i[1]
          elsif  i[0] == "Income"
            result[1][1] += i[1]
          end
        end
        return result
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/group_expenses_helper.rb
module GroupExpensesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/wallets_helper.rb
module WalletsHelper
end

app/views/layouts/_dashboard.html.erb
<ul class="nav nav-tabs justify-content-center nav-justified">
  <li class="nav-item">
    <a class="nav-link " aria-current="page" href=<%=root_path%>>Dashboard</a>
  </li>
  <li class="nav-item">
    <a class="nav-link"   href=<%=transactions_path%>>Transaction</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href=<%=accounts_path%>>Accounts</a>
  </li>
   <li class="nav-item">
    <a class="nav-link" href=<%=groups_path%>>Group Expense</a>
  </li>
  

  <%# new_user_invitation_path%  %>
</ul>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <div class=col-4>
     <% if user_signed_in?%>

      <a class="navbar-brand " href="#"><%=current_user.first_name%></a>
   
    <% else %>

      <a class="navbar-brand " href="#">Expense Manager</a>
  
    <% end %>
     </div>
    
    <div class="col-8">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0" style="float:right;">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Home</a>
          </li>
        <% if user_signed_in?%>
         
          
           <li class="nav-item">
            <a class="nav-link" href=<%=destroy_user_session_path%> data-method="delete">Sign Out</a>
          </li>
         <% else %> 
          <li class="nav-item">
            <a class="nav-link" href=<%=user_session_path%>>Sign In</a>
          </li>
          <% end %>

          
        
       
          
        </ul>
    </div>
      
    </div>
  </div>
 </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ema</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %> 
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script> 
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %> 
  </head>

  <body>

       <div class="container-fluid">
        
      <div class="row">
      
          <div class="col-12">
            <%= render partial:"layouts/navbar"%>
          </div>

          <div class="col-4">
          </div>

          <div class="col-4">
             <p class="notice"><%= notice %></p>
             <p class="alert"><%= alert %></p>

             <% if user_signed_in?%>
               <%= render partial:"layouts/dashboard"%>
             <% end %>   

          </div>

          <div class="col-4">
          </div>

        </div> 
      
  
      <div class="row">
      
        <% if user_signed_in?%>

           <div class="col-12">
             <%= yield %>
           </div>

        <% else %>

          <div class="col-4">
          </div>
          
          <div class="col-4 justify-center">
            <%= yield %>
          </div>

          <div class="col-4">
          </div>

        <% end %>
        
      </div>
     </div>
  </body>
</html>