config/routes.rb
Rails.application.routes.draw do

  
  resources :groups do 
    resources :group_expenses
  end
  resources :transactions
  resources :wallets
  resources :accounts
  resources :income, controller: "transactions", type: "income"
  resources :expense, controller: "transactions", type: "expense"
  resources :transfer, controller: "transactions", type: "transfer"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root to:"public#homepage"

  devise_for :users, controllers: {
    registrations: 'user/registrations',
    invitations: 'user/invitations',
  }  
          # get      '*path'       => redirect('/404') 
end

app/models/account.rb
class Account < ApplicationRecord
    belongs_to :user
    has_many :transactions, as: :transaction_to
    has_many :transactions, as: :transaction_from
    
    validates :accountnumber,:accountname, uniqueness: true

    validates :accountnumber, :accountname, :accountbalance, presence: true
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: %i[ show edit update destroy ]
  # before_action :can_modify_post, only: %i[ show edit update destroy ]
  

  # GET /accounts or /accounts.json
  def index
    @accounts = current_user.accounts
    @wallet = current_user.wallet
    authorize @accounts
  end

  # GET /accounts/1 or /accounts/1.json
  def show
    authorize @account
    # if authorize @account != true

    # end
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
    authorize @account
  end

  # POST /accounts or /accounts.json
  def create
    # authorize @accounts
    @account = Account.new(account_params)
    @account.user_id=current_user.id
    if @account.save
      redirect_to @account, notice: "Account was successfully created." 
    else
      render :new
    end
  end

  # PATCH/PUT /accounts/1 or /accounts/1.json
  def update
    
      if @account.update(account_params)
        redirect_to @account, notice: "Account was successfully updated." 
      else
       render :edit, status: :unprocessable_entity 
      end
    
  end

  # DELETE /accounts/1 or /accounts/1.json
  def destroy
    authorize @account
    @account.destroy
    redirect_to accounts_url, notice: "Account was successfully destroyed." 
  end
 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
      # authorize @accounts
    end
    # def can_modify_post
    #   redirect_to( accounts_url,) and return unless  @account.user_id==current_user.id
    # end


    # Only allow a list of trusted parameters through.
    def account_params
      params.require(:account).permit(:accountnumber, :accountname, :accounttype, :accountbalance)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
   <% if @account.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>
        <ul>
          <% @account.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %> 
<%= simple_form_for @account do |form| %>
  <div class="row">
    <div class="col-4">
    </div>
    <div class="col-4">
      <div class="from-group">
        <%= form.label :accountnumber %>
        <%= form.number_field :accountnumber, required: true,class:"form-control", min: 1 %>
      </div>

      <div class="from-group">
        <%= form.label :accountname %>
        <%= form.text_field :accountname ,required: true,class:"form-control"%>
      </div>

      <div class="from-group">
        <%= form.label :accounttype %>
        <%= form.text_field :accounttype ,required: true,class:"form-control"%>
      </div>

      <div class="from-group">
        <%= form.label :accountbalance %>
        <%= form.number_field :accountbalance,required: true,class:"form-control", min: 1 %>
      </div>

      <div class="actions">
        <%= form.button :submit, class: 'btn btn-success' %>
      </div>
      
    </div>
    <div class="col-4">
    </div>
  </div>
<% end %>
  

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Show', @account,class: 'btn btn-outline-info btn-xs'  %> |
<%= link_to 'Back', accounts_path ,class: 'btn btn-outline-success btn-xs' %>

app/views/accounts/index.html.erb
<h1>Accounts</h1>

<table class="table">
  <thead class="table-dark">
    <tr>
      <th scope="col">Accountnumber</th>
      <th scope="col">Accountname</th>
      <th scope="col">Accounttype</th>
      <th scope="col">Accountbalance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.accountnumber %></td>
        <td><%= account.accountname %></td>
        <td><%= account.accounttype %></td>
        <td><%= account.accountbalance %></td>
        <td><%= link_to 'Show', account , class: 'btn btn-outline-info btn-xs' %></td>
        <td><%= link_to 'Edit', edit_account_path(account), class: 'btn btn-outline-warning btn-xs'  %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } , class: 'btn btn-outline-danger btn-xs'  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path ,class: 'btn btn-outline-dark btn-xs'%>


<h1>Wallets</h1>

<table class="table">
  <thead class="table-dark">
    <tr>
      <th scope="col">Walletbalance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= @wallet.walletbalance %></td>
      <td><%= link_to 'Show', @wallet , class: 'btn btn-outline-info btn-xs'%></td>
      <td><%= link_to 'Edit', edit_wallet_path(@wallet) , class: 'btn btn-outline-warning btn-xs'%></td>
      <%# <td><%= link_to 'Destroy', @wallet, method: :delete, data: { confirm: 'Are you sure?' } %>
    </tr>
  </tbody>
</table>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Back', accounts_path ,class: 'btn btn-outline-success btn-xs'  %>

app/views/accounts/show.html.erb
<div class="row">
  <div class="col-4">
  </div>
  <div class="col-4">
  <table class="table">
  
  <tbody>
    <tr>
      <th scope="row">Accountnumber:</th>
      <td><%= @account.accountnumber %></td>
      
    </tr>
    <tr>
      <th scope="row">Accountname:</th>
      <td><%= @account.accountname %></td>
      
    </tr>
    <tr>
      <th scope="row">Accounttype:</th>
      <td> <%= @account.accounttype %></td>
    </tr>
    <tr>
      <th scope="row">Accountbalance:</th>
      <td> <%= @account.accountbalance %></td>
    </tr>
  </tbody>
</table>
<%= link_to 'Edit', edit_account_path(@account) , class: 'btn btn-outline-warning btn-xs' %> | 
<%= link_to 'Back', accounts_path ,class: 'btn btn-outline-success btn-xs'  %>

  </div>
  <div class="col-4">
  </div>
</div>